UPSERT = 'UPSERT'
UPSERT_INSERT = 'UPSERT_INSERT'
UPSERT_UPDATE = 'UPSERT_UPDATE'
CREATE = 'CREATE'
UPDATE = 'UPDATE'
SEARCH = 'SEARCH'
FETCH = 'FETCH'

LEADS = 'LEADS'
CUSTOMERS = 'CUSTOMERS'
SITES = 'SITES'
CONTACTS = 'CONTACTS'
OPPORTUNITIES = 'OPPORTUNITIES'
JOBS = 'JOBS'
ASSETS = 'ASSETS'
CUSTOMER_INVOICES = 'CUSTOMER_INVOICES'
PURCHASE_ORDERS = 'PURCHASE_ORDERS'
SUPPLIER_INVOICES = 'SUPPLIER_INVOICES'
EVENTS = 'EVENTS'
TASKS = 'TASKS'
NOTES = 'NOTES'
LINES_DESCRIPTION = 'LINES_DESCRIPTION'
TAX_CODES = 'TAX_CODES'
ACCOUNT_CODES = 'ACCOUNT_CODES'

REQUEST = 'request'
RESPONSE = 'response'

PLACEHOLDER_HEAVEN = "Yiati xeri o ouranos."
PLACEHOLDER_HEART = "I kardia den ekhi kimithi."
PLACEHOLDER_HOLD = "Kratiste yia mia akomi imera."

FM_DN = 'https://uatapi.fieldmagic.co'